### ISSUE TITLE
Missing bridgeCompleteUrl and bridgeCompleteMethod attributes for Bridge verb

### ISSUE THREAD

**Issue by alex-wirebee** [Bandwidth/node-sdk#20]
According to the documentation for the Bridge Verb (https://dev.bandwidth.com/docs/voice/bxml/bridge), there should be bridgeCompleteUrl and bridgeCompleteMethod attributes.
Those are missing from the current implementation:
https://github.com/Bandwidth/node-sdk/blob/88b0184f9b9aa1abe22fd28adca525b54a4b7fd0/models/bxml/verbs/Bridge.ts#L3

**Comment by ckoegel** [comment]
@alex-wirebee v1.0.2 should fix this, let us know if you find any other issues!
